# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Import here.

import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [2]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '/workspaces/ds-fall-2025-wed-D.T/Week-02-Pandas-Part-2-and-DS-Overview/data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [3]:
# Count by hand. (lol kidding)
df_food.shape[0]

125

What are the columns and their types in this data set?

In [4]:
# Show the column names and their types.

df_food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [5]:
# Remove ‘em.
df_food_day_weight_gender = df_food[['calories_day', 'weight', 'Gender']]
df_food_day_weight_gender

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [6]:
# Count ‘em.

df_food_day_weight_gender.isna().sum().iloc[:].sum()

np.int64(21)

We gotta remove those `NaN`s―the entire row.

In [7]:
# Drop ‘em.

df_food_3_cleaned = df_food_day_weight_gender.dropna()

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [8]:
# Fix that.
df_food_3_cleaned['weight'] = pd.to_numeric(df_food_3_cleaned['weight'], errors="coerce")
df_food_3_cleaned.dropna()

/tmp/ipykernel_69828/2362649128.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_food_3_cleaned['weight'] = pd.to_numeric(df_food_3_cleaned['weight'], errors="coerce")

     calories_day  weight  Gender
1             3.0   155.0       1
4             2.0   190.0       1
5             3.0   190.0       1
6             3.0   180.0       2
7             3.0   137.0       1
..            ...     ...     ...
118           3.0   140.0       1
119           3.0   185.0       2
120           4.0   156.0       1
121           2.0   180.0       1
123           4.0   135.0       2

[101 rows x 3 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [9]:
# Savey save!
df_food_3 = df_food_3_cleaned
df_food_3.to_csv('/workspaces/ds-fall-2025-wed-D.T/Week-02-Pandas-Part-2-and-DS-Overview/data/food_cleaned_3cols.csv', index=False)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [10]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).

df_manager_salary_survey = pd.read_table('/workspaces/ds-fall-2025-wed-D.T/Week-02-Pandas-Part-2-and-DS-Overview/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv')

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

In [11]:
columns = []

for col in df_manager_salary_survey.columns:
    columns.append(col.replace(" ", "_").lower())

df_manager_salary_survey.columns = columns
df_manager_salary_survey.to_csv('/workspaces/ds-fall-2025-wed-D.T/Week-02-Pandas-Part-2-and-DS-Overview/data/manager_salary_survey.csv',index=False)
# df_manager_salary_survey.columns = columns

### Explore

You know the drill.

How much data did you just load?

In [12]:
# Count by hand. I’m dead serious.

df_manager_salary_survey.shape[0]

28062

What are the columns and their types?

In [13]:
# Show the column names and their types.

df_manager_salary_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   timestamp                                                                                                                                                                                                                             28062 non-null  object
 1   how_old_are_you?                                                                                                                                                                                                                      28062 non-null  object
 2   what_industry_do_you_work_in?                                                                                                                                                                                                         27988 non-null  object
 3   job_title                                                                                                                                                                                                                             28061 non-null  object
 4   if_your_job_title_needs_additional_context,_please_clarify_here:                                                                                                                                                                      7262 non-null   object
 5   what_is_your_annual_salary?_(you'll_indicate_the_currency_in_a_later_question._if_you_are_part-time_or_hourly,_please_enter_an_annualized_equivalent_--_what_you_would_earn_if_you_worked_the_job_40_hours_a_week,_52_weeks_a_year.)  28062 non-null  object
 6   how_much_additional_monetary_compensation_do_you_get,_if_any_(for_example,_bonuses_or_overtime_in_an_average_year)?_please_only_include_monetary_compensation_here,_not_the_value_of_benefits.                                        20766 non-null  float64
 7   please_indicate_the_currency                                                                                                                                                                                                          28062 non-null  object
 8   if_"other,"_please_indicate_the_currency_here:_                                                                                                                                                                                       206 non-null    object
 9   if_your_income_needs_additional_context,_please_provide_it_here:                                                                                                                                                                      3042 non-null   object
 10  what_country_do_you_work_in?                                                                                                                                                                                                          28062 non-null  object
 11  if_you're_in_the_u.s.,_what_state_do_you_work_in?                                                                                                                                                                                     23039 non-null  object
 12  what_city_do_you_work_in?                                                                                                                                                                                                             27980 non-null  object
 13  how_many_years_of_professional_work_experience_do_you_have_overall?                                                                                                                                                                   28062 non-null  object
 14  how_many_years_of_professional_work_experience_do_you_have_in_your_field?                                                                                                                                                             28062 non-null  object
 15  what_is_your_highest_level_of_education_completed?                                                                                                                                                                                    27840 non-null  object
 16  what_is_your_gender?                                                                                                                                                                                                                  27891 non-null  object
 17  what_is_your_race?_(choose_all_that_apply.)                                                                                                                                                                                           27885 non-null  object
dtypes: float64(1), object(17)
memory usage: 3.9+ MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [14]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_manager_salary_survey.columns = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed', 'gender', 'race']

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [15]:
# List the unique industries and a count of their instances.
df_manager_salary_survey['industry'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 28062 entries, 0 to 28061
Series name: industry
Non-Null Count  Dtype
--------------  -----
27988 non-null  object
dtypes: object(1)
memory usage: 219.4+ KB

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [16]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)
df_manager_salary_survey['industry'].unique()
# "Computing or Tech"

condition = df_manager_salary_survey['industry'] == 'Computing or Tech'
df_tech_manager_salary = df_manager_salary_survey[condition]

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [17]:
# Sanity Check 
df_tech_manager_salary['industry'].unique()

array(['Computing or Tech'], dtype=object)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [18]:
# Filtery filter for just the jobs that pay in USD!

df_tech_manager_salary['currency']
# USD

condition2 = df_tech_manager_salary['currency'] == 'USD'
df_tech_manager_salary_USD = df_tech_manager_salary[condition2]
df_tech_manager_salary_USD

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000,0.0,USD,NaN,NaN,United States,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [19]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_tech_manager_salary_USD['country'].value_counts(ascending=False)

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [47]:
# Replace them all with 'US'

# Replace them all with 'US'

df_usd = df_tech_manager_salary_USD.copy()

countries = ['United States', 'USA', 'US', 'U.S.', 'United States of America']

for country in countries:
    df_usd['country'] = np.where(df_usd['country'] == country, 'US', df_usd['country'])

Have a look at the count of each unique country again now.

In [48]:
# Count again.
df_usd['country'].value_counts(ascending=False)

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
                  ...
Ghana                1
Nigeria              1
ss                   1
Nigeria              1
Burma                1
Name: count, Length: 72, dtype: int64

Did you notice anything interesting?

In [49]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [50]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [51]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

condition3 = df_usd['country'] == 'US'
df_usd[condition3].groupby(['country', 'state'])['salary'].agg(['mean', 'min', 'max'])

TypeError: agg function failed [how->mean,dtype->object]

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [52]:
# Fix it.
df_usd['salary'] = df_usd['salary'].str.replace(",", "")
df_usd['salary'] = pd.to_numeric(df_usd['salary'])

Let’s try that again.

In [53]:
# Try it again. Yeah!
condition3 = df_usd['country'] == 'US'
df_usd[condition3].groupby(['country', 'state'])['salary'].agg(['mean', 'min', 'max'])

                                                mean     min     max
country state
US      Alabama                         74457.777778   29120  120000
        Alabama, District of Columbia  156000.000000  156000  156000
        Alabama, Montana                72000.000000   72000   72000
        Alaska                         112500.000000   67000  158000
        Arizona                        103893.939394   35000  210000
...                                              ...     ...     ...
        Vermont                        111781.250000   65000  200000
        Virginia                       129387.704762   43642  450000
        Washington                     150592.449367      72  950000
        West Virginia                  120500.000000  116500  125000
        Wisconsin                      113891.371795       1  920000

[63 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [59]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_usd['timestamp'] = pd.to_datetime(df_usd['timestamp'], errors='coerce')
df_usd_21_to_23 = df_usd[df_usd['timestamp'].dt.year.isin([2021, 2022, 2023])]
condition4 = df_usd_21_to_23['country'] == 'US'
df_usd_21_to_23[condition4].groupby(['country', 'state'])['salary'].agg(['mean', 'min', 'max'])

                                                mean     min     max
country state
US      Alabama                         74457.777778   29120  120000
        Alabama, District of Columbia  156000.000000  156000  156000
        Alabama, Montana                72000.000000   72000   72000
        Alaska                         112500.000000   67000  158000
        Arizona                        103893.939394   35000  210000
...                                              ...     ...     ...
        Vermont                        111781.250000   65000  200000
        Virginia                       129387.704762   43642  450000
        Washington                     150749.409524      72  950000
        West Virginia                  120500.000000  116500  125000
        Wisconsin                      113891.371795       1  920000

[63 rows x 3 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)